var GAME_LEVELS = [
  ["                            xxx  xxx      x      x                                                         ",
   "                            xxx!!xxx       x!!!!!x                                                         ",
   "                              x!!x          x!!x v                                                         ",
   "                              x!!x           xx                                                            ",
   "                              xxxx           oo                                                            ",
   "                                v                                                                          ",
   "                                                                  xxx                                      ",
   "                        oo                         xx      xx    xx!xx                                     ",
   "                                    o o      xx                  x!vxx              xxx                    ",
   "  x!!!x               xxx                                        xx xx                                     ",
   "  x v x                                  xxxxx                             xxx         xxx                 ",
   "  x                   y                                                                                    ",
   "  x                xxxx                     o o                                           oo               ",
   "  x              xx      o                                                            yy     yy            ",
   "  x             xx                         oo                     o x             yy  xxxx   xxxx          ",
   "  x          xxxx       oooo                                                      xxxx   x!!!x             ",
   "  x  @                       yy        xx  xx   xxx                xxxxx  yy  xxxx       x!!!x             ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxx          xxxxxx   x     xxxxxxxxxxxxx           x!!!x             ",
   "                              x!!!x    x!!!!!!!!!!x    x!!!x    x                        x!!!x             ",
   "                              x!!!x    x!!!!!!!!!!x    x!!!x   x                         xxxxx             ",
   "                              xxxxx    xxxxxxxxxxxx    x!!!x  x                                            ",
   "                                                       xxxxx x                                             ",
   "                                                           xx                                              ",
   "                                                                                                           "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                              xxxx        x!!xxxxxxxxxx           xx           xx                            x!x  ",
   "                                            xx             xx                                                x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                        xxxx                        xx!x         x     o   o                                xx!x  ",
   "            o                                     x!x         x                               xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "        o              xxxx                                        xx!!!!!!!!!!!xx       v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                        xxx       x     x            xxxxxxx        xxx         xxx               ",
   "                               o                x     x                           x x         x x                 ",
   "            o        xxxx   o      xxxx                  x     x                             x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                              x     x      o  o     x   x         x         x                     ",
   "    o                  xxx   xxx        x     x               x   x         x         x                           ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xxxxxxxxxxxx        x o x          x    xx               x   x   x               x                   ",
   "     @      xxx         x        x   x          x     x               x   x   x               x                   ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "                                                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                              x          x                                                    ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                           xxxxxxxxxxxx       xxx                                                             ",
   "                                     xx   xx      x   x      x                                                ",
   "                        xxxxxxxx              x x                                                             ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                             = = = =x     o      xxx       xxx                                                ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                                 x     x                xxv        xxx                                        ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                  o o  x!!!!!!!!!!!!!!x                   vx                                                  ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x                                                                  ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                               xxx    xxxxxxx                        xxxxx                              x  ",
   "  x                                    x                              x   x                                x  ",
   "  x                                     x                              x x x                               x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x                    xx          x                             xxx       x!!!x          x                x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @                  x           x!!x    x!!!!x    x!!!!x    xx   xx                    x           x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                                                                   ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
